alter session set "_ORACLE_SCRIPT"=true;  
CREATE USER ECommerce IDENTIFIED BY ECommerce123;
GRANT CREATE SESSION TO ECommerce;
GRANT CONNECT, RESOURCE, DBA TO ECommerce;


CREATE TABLE ECommerce.Person
  (
    Person_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 1 PRIMARY KEY,
    Person_firstName VARCHAR2( 50 ) NOT NULL,
    Person_lastName VARCHAR2( 50 ) NOT NULL,
    Person_phone VARCHAR2( 50 ) NOT NULL,
    Person_address VARCHAR2( 250 ) NOT NULL
     );
  
  CREATE TABLE ECommerce.Orders
  (
    Order_id NUMBER GENERATED BY DEFAULT AS IDENTITY 
    START WITH 1 PRIMARY KEY,
    Order_amount     NUMBER( 12, 0 ) ,
    Order_date      DATE ,
    Order_quantity      NUMBER( 12, 0 ),
    Person_id NUMBER,
    Product_id NUMBER,
    CONSTRAINT fk_Orders_Product 
      FOREIGN KEY( Product_id )
      REFERENCES ECommerce.Product( Product_id ) 
      ON DELETE CASCADE,
      CONSTRAINT fk_Orders_Person
      FOREIGN KEY( Person_id )
      REFERENCES ECommerce.Person( Person_id ) 
      ON DELETE CASCADE
  );
  CREATE TABLE ECommerce.Product
  (
    Product_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 1 PRIMARY KEY,
    Product_name  VARCHAR( 255 ),
    Product_detail VARCHAR( 255 ),
    
    Stock_Quantity  NUMBER( 12, 0 ),
    Price           NUMBER( 12, 0 )
    );
    
    
    SELECT
        *
    FROM ECommerce.Product
    
    Insert into ECommerce.Person (Person_id,Person_firstName,Person_lastName,Person_phone,Person_address) values (1,'Berfin','Aydýn','05388569456','Kocaeli');
    Insert into ECommerce.Person (Person_id,Person_firstName,Person_lastName,Person_phone,Person_address) values (2,'Ali','Ayar','05387669756','Ýzmir');
    Insert into ECommerce.Person (Person_id,Person_firstName,Person_lastName,Person_phone,Person_address) values (3,'Ahmet','Kara','05796469456','Ankara');
    
    
    
    Insert into ECommerce.Product (Product_id,Product_name,Product_detail,Stock_Quantity,Price) values (1,'Kalem','turuncu',421,13);
    Insert into ECommerce.Product (Product_id,Product_name,Product_detail,Stock_Quantity,Price) values (2,'Bardak','kýrmýzý',756,'15');
    Insert into ECommerce.Product (Product_id,Product_name,Product_detail,Stock_Quantity,Price) values (3,'Tabak','siyah',365,36);
    
    
     Insert into ECommerce.Orders (Order_id,Order_amount,Order_date,Order_quantity,Person_id,Product_id) values (1,265,'12/08/2020',24,1,2);
     Insert into ECommerce.Orders (Order_id,Order_amount,Order_date,Order_quantity,Person_id,Product_id) values (2,150,'17/04/2020',28,2,3);
     Insert into ECommerce.Orders (Order_id,Order_amount,Order_date,Order_quantity,Person_id,Product_id) values (3,350,'13/02/2020',21,3,1);
    
    
    
     CREATE VIEW Urun_getir AS
    SELECT Product_name, Product_detail, Price FROM ECommerce.Product
    WHERE Price>10;
 